apiVersion: cert-manager.io/v1
kind: CertificateRequest
metadata:
  name: clusterissuer-sample
spec:
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQllUQ0NBUWdDQVFBd01ERXVNQ3dHQTFVRUF4TWxiWGt0Y0c5a0xtMTVMVzVoYldWemNHRmpaUzV3YjJRdQpZMngxYzNSbGNpNXNiMk5oYkRCWk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQkFCcVpNYXBxcDFFCkZqVGlMOG5GZkxwOFNTcmxQWFRzLzVLSG1PL3grYmtHZ1Q2bGJjL3FPampVSlhlV2xpZWxPS2o0NG9PYklKMVIKMXN1SmdLL3BZd1dnZGpCMEJna3Foa2lHOXcwQkNRNHhaekJsTUdNR0ExVWRFUVJjTUZxQ0pXMTVMWE4yWXk1dAplUzF1WVcxbGMzQmhZMlV1YzNaakxtTnNkWE4wWlhJdWJHOWpZV3lDSlcxNUxYQnZaQzV0ZVMxdVlXMWxjM0JoClkyVXVjRzlrTG1Oc2RYTjBaWEl1Ykc5allXeUhCTUFBQWhpSEJBb0FJZ0l3Q2dZSUtvWkl6ajBFQXdJRFJ3QXcKUkFJZ0Q2T2JROUNScXZ2MUYzc01PeGZRRWdrZEdyTlR3UDE5eGQ5RFVQZ24vUHNDSURIS0k0UlBxK3V2QW5KSwplanU0THcyUDh2QjVHY3ZRcCs5amhCMVdiVFZpCi0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  issuerRef:
    name: clusterissuer-sample
    group: sample-issuer.example.com
    kind: ClusterIssuer
